apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: db-password
        secret:
          secretName: {{ .Values.backend.env.DB_PASSWORD_SECRET }}

      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}

        env:
        - name: DB_HOST
          value: "{{ .Values.backend.env.DB_HOST }}"
        - name: DB_PORT
          value: "{{ .Values.backend.env.DB_PORT }}"
        - name: DB_USER
          value: "{{ .Values.backend.env.DB_USER }}"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.env.DB_PASSWORD_SECRET }}
              key: {{ .Values.backend.env.DB_PASSWORD_KEY }}

        volumeMounts:
        - name: db-password
          mountPath: "/run/secrets"
